### ISSUE TITLE
issue in Learn ReactJS

### ISSUE THREAD

**Issue by ShubhajitPaul-2** [shubhajit-paul-web/git-demo#4]
Note down this point:

Learn ReactJS but at first, learn advanced javascript before learning ReactJS for you able to learn very in-depth knowledge about ReactJS...

**Comment by shubhajit-paul-web** [comment]
Thanks for tell me

**Comment by shubhajit-paul-web** [comment]
#4 Thank you for telling me about this Important topic.

**Comment by shubhajit-paul-web** [comment]
#4 okay thanks Done

**Comment by shubhajit-paul-web** [comment]
Done bro
